version: '2.3'
services:
  q-server:
    build:
      context: ./build
    # image: tonlabs/q-server:latest
    container_name: q-server
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=q-server
      - VIRTUAL_PORT=4000
      - Q_DATA_MUT
      - Q_DATA_HOT
      - Q_REQUESTS_MODE
      - Q_REQUESTS_SERVER
      - Q_REQUESTS_TOPIC
      - Q_QUERY_MAX_RUNTIME
      - Q_SLOW_QUERIES
      - Q_REMP_ENABLED
      - Q_REMP_REDIS_CLIENT_URL
    networks:
      - proxy_nw
    expose:
      - "4000"
    mem_limit: 5G
networks:
  proxy_nw:
    external: true
