version: '2.3'
services:
  arangodb:
    build:
      context: ./build
    # image: tonlabs/arango:latest
    container_name: arangodb
    restart: unless-stopped
    environment:
      ARANGO_NO_AUTH: 1
      VIRTUAL_HOST: arango.yourdomain.com
      VIRTUAL_PORT: 8529
      LETSENCRYPT_HOST: arango.yourdomain.com
      LETSENCRYPT_EMAIL: "email for notification"
      ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY: 343579738368
    networks:
      - proxy_nw
    volumes:
      - db3:/var/lib/arangodb3
      - data:/arango/db
      - ./arango-config:/arango/config
    expose:
      - "8529"
    mem_limit: 32G

networks:
  proxy_nw:
    external: true
volumes:
  data:
  db3:
  datani:
  db3ni:
